version: "3.6"

services:
  gateway:
    build: .
    ports:
      - "65080:9080"
    image: k830206/signoz-gateway:latest
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9080/ticker/list"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  default:
    name: projectset
