server.port: 9080
logging.level.org.springframework.cloud.gateway: TRACE
management.endpoints.web.exposure.include: '*'
namespace: acornworks
management:
  endpoint:
    health:
      group:
        custom:
          include: diskSpace,ping
          show-components: always
          show-details: always
spring.cloud:
  discovery.enabled: false
  gateway:
    globalcors:
      cors-configurations:
        '[/**]':
          allowedOrigins:
            - "*"
          allowedMethods:
            - GET
            - POST
            - DELETE
            - PUT
            - OPTION
    routes:
      - id: Ticker Route
        uri: http://ticker.${namespace}.svc:65010
        predicates:
        - Path=/ticker/**
        filters:
        - RewritePath=/(?<url>.*), /${url}
      - id: Price Route
        uri: http://price.${namespace}.svc:65020
        predicates:
        - Path=/price/**
        filters:
        - RewritePath=/(?<url>.*), /${url}
      - id: Strategy Route
        uri: http://strategy.${namespace}.svc:65030
        predicates:
        - Path=/strategy/**
        filters:
        - RewritePath=/(?<url>.*), /${url}

